import type { EntityConfig } from "./types";

const sensitivity = ["public", "internal_only", "private", "client_confidential", "coi_review"];
const permissionLevels = [
  "internal_only",
  "owner_approved",
  "client_approved",
  "public_safe",
  "restricted",
];
const redactionStatuses = ["not_reviewed", "needs_redaction", "redacted", "public_safe", "restricted"];

export const entityConfigs: EntityConfig[] = [
  {
    id: "engagements",
    title: "Engagements",
    shortTitle: "Engagements",
    table: "private_dtp_engagements",
    description: "Private workstreams and client/project lanes.",
    sortBy: "updated_at",
    display: ["client_or_project_alias", "stage", "sensitivity", "source_repo"],
    fields: [
      { key: "title", label: "Title", kind: "text", required: true },
      { key: "client_or_project_alias", label: "Alias", kind: "text", required: true },
      {
        key: "kind",
        label: "Kind",
        kind: "select",
        required: true,
        options: ["client", "internal", "product", "proof_track", "family_private"],
      },
      {
        key: "stage",
        label: "Stage",
        kind: "select",
        required: true,
        options: ["intake", "diagnose", "plan", "build", "handoff", "support", "proof_review", "archived"],
      },
      { key: "sensitivity", label: "Sensitivity", kind: "select", required: true, options: sensitivity },
      { key: "owner", label: "Owner", kind: "text" },
      { key: "source_repo", label: "Source repo", kind: "text" },
      { key: "local_pointer", label: "Local pointer", kind: "text" },
    ],
  },
  {
    id: "artifacts",
    title: "Artifact Inventory",
    shortTitle: "Artifacts",
    table: "private_dtp_artifacts",
    description: "Pointers to files, notes, reports, evidence, and assets.",
    sortBy: "updated_at",
    queueStatusField: "redaction_status",
    queueStatuses: ["not_reviewed", "needs_redaction", "restricted"],
    display: ["artifact_type", "source_kind", "redaction_status", "proof_eligibility"],
    fields: [
      { key: "engagement_id", label: "Engagement ID", kind: "text", required: true },
      {
        key: "artifact_type",
        label: "Type",
        kind: "select",
        required: true,
        options: ["note", "kit_doc", "screenshot", "report", "evidence", "runbook", "decision", "asset", "other"],
      },
      { key: "title", label: "Title", kind: "text", required: true },
      {
        key: "source_kind",
        label: "Source",
        kind: "select",
        required: true,
        options: ["local_markdown", "repo_file", "ci_artifact", "upload", "external_link", "hub_reference"],
      },
      { key: "source_pointer", label: "Source pointer", kind: "text", required: true },
      { key: "storage_pointer", label: "Storage pointer", kind: "text" },
      { key: "summary", label: "Summary", kind: "textarea" },
      { key: "data_class", label: "Data class", kind: "select", options: ["P0", "P1", "P2", "P3"] },
      { key: "permission_level", label: "Permission", kind: "select", options: permissionLevels },
      { key: "redaction_status", label: "Redaction", kind: "select", options: redactionStatuses },
      { key: "proof_eligibility", label: "Proof", kind: "select", options: ["not_candidate", "candidate", "approved", "rejected"] },
    ],
  },
  {
    id: "evidence",
    title: "Evidence Runs",
    shortTitle: "Evidence",
    table: "private_dtp_evidence_runs",
    description: "Verification receipts across local, CI, release, support, and proof lanes.",
    sortBy: "created_at",
    queueStatusField: "result",
    queueStatuses: ["fail", "manual_pending", "not_checked"],
    display: ["repo", "lane", "result", "hard_gate_status"],
    fields: [
      { key: "engagement_id", label: "Engagement ID", kind: "text" },
      { key: "repo", label: "Repo", kind: "text", required: true },
      { key: "branch", label: "Branch", kind: "text" },
      { key: "commit_sha", label: "Commit", kind: "text" },
      { key: "lane", label: "Lane", kind: "select", required: true, options: ["local", "ci", "release", "support", "proof", "manual"] },
      { key: "result", label: "Result", kind: "select", required: true, options: ["pass", "fail", "advisory_pass", "manual_pending", "not_checked"] },
      { key: "commands", label: "Commands", kind: "array" },
      { key: "hard_gate_status", label: "Hard gate", kind: "text" },
      { key: "advisory_gate_status", label: "Advisory gate", kind: "text" },
      { key: "manual_gate_status", label: "Manual gate", kind: "text" },
      { key: "artifact_path", label: "Artifact path", kind: "text" },
      { key: "redaction_status", label: "Redaction", kind: "select", options: redactionStatuses },
      { key: "reviewer", label: "Reviewer", kind: "text" },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  {
    id: "redaction",
    title: "Redaction Queue",
    shortTitle: "Redaction",
    table: "private_dtp_redaction_reviews",
    description: "Review items for artifacts, evidence, and proof candidates.",
    sortBy: "updated_at",
    queueStatusField: "status",
    queueStatuses: ["not_started", "needs_changes"],
    display: ["target_type", "status", "permission_level", "reviewer"],
    fields: [
      { key: "engagement_id", label: "Engagement ID", kind: "text" },
      { key: "target_type", label: "Target type", kind: "select", required: true, options: ["artifact", "evidence_run", "proof_candidate"] },
      { key: "target_id", label: "Target ID", kind: "text", required: true },
      { key: "reviewer", label: "Reviewer", kind: "text" },
      { key: "status", label: "Status", kind: "select", required: true, options: ["not_started", "needs_changes", "approved_internal", "approved_public", "rejected"] },
      { key: "permission_level", label: "Permission", kind: "select", required: true, options: permissionLevels },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  {
    id: "proof",
    title: "Proof Queue",
    shortTitle: "Proof",
    table: "private_dtp_proof_candidates",
    description: "Possible proof claims with evidence, permission, and redaction gates.",
    sortBy: "updated_at",
    queueStatusField: "status",
    queueStatuses: ["proposed", "needs_evidence", "needs_permission", "parked"],
    display: ["status", "permission_status", "redaction_status", "reviewer"],
    fields: [
      { key: "engagement_id", label: "Engagement ID", kind: "text", required: true },
      { key: "artifact_id", label: "Artifact ID", kind: "text" },
      { key: "public_claim", label: "Claim", kind: "textarea" },
      { key: "baseline", label: "Baseline", kind: "textarea" },
      { key: "after_state", label: "After state", kind: "textarea" },
      { key: "metric", label: "Metric", kind: "text" },
      { key: "caveat", label: "Caveat", kind: "textarea" },
      { key: "evidence_source", label: "Evidence source", kind: "text" },
      { key: "permission_status", label: "Permission", kind: "select", options: ["not_requested", "owner_approved", "client_approved", "public_safe", "rejected", "restricted"] },
      { key: "redaction_status", label: "Redaction", kind: "select", options: ["not_reviewed", "needs_redaction", "approved_internal", "approved_public", "public_safe", "rejected"] },
      { key: "reviewer", label: "Reviewer", kind: "text" },
      { key: "status", label: "Status", kind: "select", required: true, options: ["proposed", "needs_evidence", "needs_permission", "approved", "rejected", "parked"] },
    ],
  },
  {
    id: "decisions",
    title: "Decisions",
    shortTitle: "Decisions",
    table: "private_dtp_decisions",
    description: "Architecture, workflow, proof, automation, and scope decisions.",
    sortBy: "updated_at",
    display: ["status", "chosen_path", "related_artifact_id", "related_evidence_run_id"],
    fields: [
      { key: "engagement_id", label: "Engagement ID", kind: "text" },
      { key: "title", label: "Title", kind: "text", required: true },
      { key: "status", label: "Status", kind: "select", required: true, options: ["proposed", "accepted", "superseded", "rejected"] },
      { key: "context", label: "Context", kind: "textarea" },
      { key: "options_considered", label: "Options", kind: "textarea" },
      { key: "chosen_path", label: "Chosen path", kind: "textarea" },
      { key: "consequences", label: "Consequences", kind: "textarea" },
      { key: "related_artifact_id", label: "Related artifact ID", kind: "text" },
      { key: "related_evidence_run_id", label: "Related evidence ID", kind: "text" },
    ],
  },
  {
    id: "steward",
    title: "Steward Items",
    shortTitle: "Steward",
    table: "private_dtp_steward_items",
    description: "Corrections, memory candidates, roadmap items, gates, and follow-ups.",
    sortBy: "updated_at",
    queueStatusField: "status",
    queueStatuses: ["open", "approved"],
    display: ["item_type", "status", "sensitivity", "destination_pointer"],
    fields: [
      { key: "title", label: "Title", kind: "text", required: true },
      { key: "item_type", label: "Type", kind: "select", required: true, options: ["correction", "memory_candidate", "roadmap_item", "blocked_gate", "follow_up"] },
      { key: "source_pointer", label: "Source pointer", kind: "text" },
      { key: "destination_pointer", label: "Destination pointer", kind: "text" },
      { key: "status", label: "Status", kind: "select", required: true, options: ["open", "approved", "promoted", "parked", "rejected", "done"] },
      { key: "sensitivity", label: "Sensitivity", kind: "select", options: sensitivity },
      { key: "human_approval", label: "Human approval", kind: "text" },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  {
    id: "research",
    title: "Research Items",
    shortTitle: "Research",
    table: "private_dtp_research_items",
    description: "Source-reviewed research items and adoption decisions.",
    sortBy: "updated_at",
    queueStatusField: "status",
    queueStatuses: ["open"],
    display: ["classification", "status", "linked_roadmap_item", "source_url"],
    fields: [
      { key: "title", label: "Title", kind: "text", required: true },
      { key: "source_url", label: "Source URL", kind: "text" },
      { key: "source_pointer", label: "Source pointer", kind: "text" },
      { key: "classification", label: "Classification", kind: "select", required: true, options: ["adopt", "pilot", "watch", "reject"] },
      { key: "decision_reason", label: "Decision reason", kind: "textarea" },
      { key: "linked_roadmap_item", label: "Roadmap item", kind: "text" },
      { key: "status", label: "Status", kind: "select", required: true, options: ["open", "accepted", "parked", "rejected", "done"] },
    ],
  },
];
